

//$$strtCprt
//
// Simple Algebra 
// 
// Copyright (C) 2014 Thornton Green
// 
// This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with this program; if not, 
// see <http://www.gnu.org/licenses>.
// Additional permission under GNU GPL version 3 section 7
//
//
//$$endCprt

package test_simplealgebra




import test_simplealgebra.TestDaqHgCompound;
import simplealgebra.ga.GeometricAlgebraMultivectorElem;
import simplealgebra.et.EinsteinTensorElem;






// Compound query that performs a join between a query of multivectors and a query of tensors.
rule "Select Join Elems"
     when
          n0 : TestDaqHgCompound.CompoundQueryContext( )
          d0 : GeometricAlgebraMultivectorElem( ) from n0.getDefaultPrimitiveQuery()
          d1 : EinsteinTensorElem( ) from n0.getCompoundPrimitiveQuery()
          eval( n0.isGeometricClose( d0 , d1 ) )
     then
          n0.getResultHandler().handle( n0.genResult( d0 , d1 ) );
end






