

//$$strtCprt
//
// Simple Algebra 
// 
// Copyright (C) 2014 Thornton Green
// 
// This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with this program; if not, 
// see <http://www.gnu.org/licenses>.
// Additional permission under GNU GPL version 3 section 7
//
//
//$$endCprt

package test_simplealgebra




import simplealgebra.store.DaqHgContext;
import simplealgebra.DoubleElem;






// Simple query to select all DoubleElem instances with a value greater than 3.0
rule "Select DoubleElems"
     when
          n0 : DaqHgContext( )
          d0 : DoubleElem( val > 3 ) from n0.getDefaultPrimitiveQuery()
     then
          n0.getResultList().add( d0 );
end






